---
services:

  discord-pushover:
    build:
      context: .
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
    networks:
      - discord-pushover
    environment:
      # Discord Bot Configuration
      DISCORD_TOKEN: your_discord_token
      # Guild and Channel IDs
      GUILD_ID: your_guild_id
      FORWARD_CHANNEL_ID: your_forward_channel_id
      # Channel IDs to monitor
      CHANNEL_ID_ONE: your_id_one_channel_id
      CHANNEL_ID_TWO: your_id_two_channel_id
      CHANNEL_ID_THREE: your_id_three_channel_id
      # Discord Webhook URLs
      CHANNEL_ID_ONE_WEBHOOK: your_id_one_webhook_url
      CHANNEL_ID_TWO_WEBHOOK: your_id_two_webhook_url
      CHANNEL_ID_THREE_WEBHOOK: your_id_three_webhook_url
      # Notification Settings (true/false)
      ENABLE_PUSHOVER: true
      ENABLE_DISCORD_NOTIF: false
      ENABLE_NTFY: false
      # Pushover Configuration
      PUSHOVER_TOKEN: your_pushover_token
      PUSHOVER_USER: your_pushover_user_key
      # NTFY Configuration
      NTFY_URL: your_ntfy_url

networks:
  discord-pushover:
